name: Build and Deploy to ACI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        run: |
          echo "${{ secrets.AZURE_REGISTRY_PASSWORD }}" | docker login ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io -u ${{ secrets.AZURE_REGISTRY_USERNAME }} --password-stdin

      - name: Build the Docker image
        run: |
          docker build -t ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/myapp:latest .

      - name: Push the Docker image
        run: |
          docker push ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/myapp:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Check if container exists
        id: check_container
        run: |
          if az container show --resource-group Foundermap_ai --name foundermapai; then
            echo "Container exists"
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "Container does not exist"
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: Deploy to ACI
        run: |
          if [ "${{ env.exists }}" = "true" ]; then
            echo "Updating existing container"
            az container update --resource-group Foundermap_ai --name foundermapai --image ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/myapp:latest
          else
            echo "Creating a new container"
            az container create --resource-group Foundermap_ai --name foundermapai --image ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/myapp:latest --cpu 1 --memory 1 --ports 8000 8501 --registry-login-server ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io --registry-username ${{ secrets.AZURE_REGISTRY_USERNAME }} --registry-password ${{ secrets.AZURE_REGISTRY_PASSWORD }}
          fi
